# my_error.py


class MyError(Exception):
    pass
